// Code generated by "stringer -type Level"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-102]
	_ = x[Warning-103]
	_ = x[Failure-104]
}

const _Level_name = "SuccessWarningFailure"

var _Level_index = [...]uint8{0, 7, 14, 21}

func (i Level) String() string {
	i -= 102
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i+102), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
