// Code generated by "stringer -type Type"; DO NOT EDIT.

package source

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotSpecified-0]
	_ = x[ServiceUser-1]
	_ = x[ServiceProviderACSE-2]
	_ = x[ServiceProviderPresentation-3]
}

const _Type_name = "NotSpecifiedServiceUserServiceProviderACSEServiceProviderPresentation"

var _Type_index = [...]uint8{0, 12, 23, 42, 69}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
