// Code generated by "stringer -type DataSetType"; DO NOT EDIT.

package commands

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Null-257]
	_ = x[NonNull-1]
}

const (
	_DataSetType_name_0 = "NonNull"
	_DataSetType_name_1 = "Null"
)

func (i DataSetType) String() string {
	switch {
	case i == 1:
		return _DataSetType_name_0
	case i == 257:
		return _DataSetType_name_1
	default:
		return "DataSetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
