// Code generated by "stringer -type Kind"; DO NOT EDIT.

package commands

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CSTORERQ-1]
	_ = x[CSTORERSP-32769]
	_ = x[CGETRQ-16]
	_ = x[CGETRSP-32784]
	_ = x[CFINDRQ-32]
	_ = x[CFINDRSP-32800]
	_ = x[CMOVERQ-33]
	_ = x[CMOVERSP-32801]
	_ = x[CECHORQ-48]
	_ = x[CECHORSP-32816]
	_ = x[NEVENTREPORTRQ-256]
	_ = x[NEVENTREPORTRSP-33024]
	_ = x[NGETRQ-272]
	_ = x[NGETRSP-33040]
	_ = x[NSETRQ-288]
	_ = x[NSETRSP-33056]
	_ = x[NACTIONRQ-304]
	_ = x[NACTIONRSP-33072]
	_ = x[NCREATERQ-320]
	_ = x[NCREATERSP-33088]
	_ = x[NDELETERQ-336]
	_ = x[NDELETERSP-33104]
	_ = x[CCANCELRQ-4095]
}

const _Kind_name = "CSTORERQCGETRQCFINDRQCMOVERQCECHORQNEVENTREPORTRQNGETRQNSETRQNACTIONRQNCREATERQNDELETERQCCANCELRQCSTORERSPCGETRSPCFINDRSPCMOVERSPCECHORSPNEVENTREPORTRSPNGETRSPNSETRSPNACTIONRSPNCREATERSPNDELETERSP"

var _Kind_map = map[Kind]string{
	1:     _Kind_name[0:8],
	16:    _Kind_name[8:14],
	32:    _Kind_name[14:21],
	33:    _Kind_name[21:28],
	48:    _Kind_name[28:35],
	256:   _Kind_name[35:49],
	272:   _Kind_name[49:55],
	288:   _Kind_name[55:61],
	304:   _Kind_name[61:70],
	320:   _Kind_name[70:79],
	336:   _Kind_name[79:88],
	4095:  _Kind_name[88:97],
	32769: _Kind_name[97:106],
	32784: _Kind_name[106:113],
	32800: _Kind_name[113:121],
	32801: _Kind_name[121:129],
	32816: _Kind_name[129:137],
	33024: _Kind_name[137:152],
	33040: _Kind_name[152:159],
	33056: _Kind_name[159:166],
	33072: _Kind_name[166:176],
	33088: _Kind_name[176:186],
	33104: _Kind_name[186:196],
}

func (i Kind) String() string {
	if str, ok := _Kind_map[i]; ok {
		return str
	}
	return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
}
