// Code generated by "stringer -type Status"; DO NOT EDIT.

package commands

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[Cancel-65024]
	_ = x[SOPClassNotSupported-274]
	_ = x[InvalidArgumentValue-277]
	_ = x[InvalidAttributeValue-262]
	_ = x[InvalidObjectInstance-279]
	_ = x[UnrecognizedOperation-529]
	_ = x[NotAuthorized-292]
	_ = x[Pending-65280]
}

const (
	_Status_name_0 = "Success"
	_Status_name_1 = "InvalidAttributeValue"
	_Status_name_2 = "SOPClassNotSupported"
	_Status_name_3 = "InvalidArgumentValue"
	_Status_name_4 = "InvalidObjectInstance"
	_Status_name_5 = "NotAuthorized"
	_Status_name_6 = "UnrecognizedOperation"
	_Status_name_7 = "Cancel"
	_Status_name_8 = "Pending"
)

func (i Status) String() string {
	switch {
	case i == 0:
		return _Status_name_0
	case i == 262:
		return _Status_name_1
	case i == 274:
		return _Status_name_2
	case i == 277:
		return _Status_name_3
	case i == 279:
		return _Status_name_4
	case i == 292:
		return _Status_name_5
	case i == 529:
		return _Status_name_6
	case i == 65024:
		return _Status_name_7
	case i == 65280:
		return _Status_name_8
	default:
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
