// Code generated by "stringer -type Reason"; DO NOT EDIT.

package abort

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NotSpecified-0]
	_ = x[Reserved-1]
	_ = x[UnexpectedPDU-2]
	_ = x[UnrecognizedPDUParameter-3]
	_ = x[UnexpectedPDUParameter-4]
	_ = x[InvalidPDUParameterValue-5]
}

const _Reason_name = "NotSpecifiedReservedUnexpectedPDUUnrecognizedPDUParameterUnexpectedPDUParameterInvalidPDUParameterValue"

var _Reason_index = [...]uint8{0, 12, 20, 33, 57, 79, 103}

func (i Reason) String() string {
	if i >= Reason(len(_Reason_index)-1) {
		return "Reason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Reason_name[_Reason_index[i]:_Reason_index[i+1]]
}
