// Code generated by "stringer -type AbortReasonType -trimprefix AbortReason"; DO NOT EDIT.

package pdu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AbortReasonNotSpecified-0]
	_ = x[AbortReasonUnexpectedPDU-2]
	_ = x[AbortReasonUnrecognizedPDUParameter-3]
	_ = x[AbortReasonUnexpectedPDUParameter-4]
	_ = x[AbortReasonInvalidPDUParameterValue-5]
}

const (
	_AbortReasonType_name_0 = "NotSpecified"
	_AbortReasonType_name_1 = "UnexpectedPDUUnrecognizedPDUParameterUnexpectedPDUParameterInvalidPDUParameterValue"
)

var (
	_AbortReasonType_index_1 = [...]uint8{0, 13, 37, 59, 83}
)

func (i AbortReasonType) String() string {
	switch {
	case i == 0:
		return _AbortReasonType_name_0
	case 2 <= i && i <= 5:
		i -= 2
		return _AbortReasonType_name_1[_AbortReasonType_index_1[i]:_AbortReasonType_index_1[i+1]]
	default:
		return "AbortReasonType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
