// Code generated by "stringer -type Reason"; DO NOT EDIT.

package reject

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-1]
	_ = x[ApplicationContextNameNotSupported-2]
	_ = x[CallingAETitleNotRecognized-3]
	_ = x[CalledAETitleNotRecognized-7]
}

const (
	_Reason_name_0 = "NoneApplicationContextNameNotSupportedCallingAETitleNotRecognized"
	_Reason_name_1 = "CalledAETitleNotRecognized"
)

var (
	_Reason_index_0 = [...]uint8{0, 4, 38, 65}
)

func (i Reason) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _Reason_name_0[_Reason_index_0[i]:_Reason_index_0[i+1]]
	case i == 7:
		return _Reason_name_1
	default:
		return "Reason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
