// Code generated by "stringer -type PresentationContextResult -trimprefix PresentationContext"; DO NOT EDIT.

package pdu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PresentationContextAccepted-0]
	_ = x[PresentationContextUserRejection-1]
	_ = x[PresentationContextProviderRejectionNoReason-2]
	_ = x[PresentationContextProviderRejectionAbstractSyntaxNotSupported-3]
	_ = x[PresentationContextProviderRejectionTransferSyntaxNotSupported-4]
}

const _PresentationContextResult_name = "AcceptedUserRejectionProviderRejectionNoReasonProviderRejectionAbstractSyntaxNotSupportedProviderRejectionTransferSyntaxNotSupported"

var _PresentationContextResult_index = [...]uint8{0, 8, 21, 46, 89, 132}

func (i PresentationContextResult) String() string {
	if i >= PresentationContextResult(len(_PresentationContextResult_index)-1) {
		return "PresentationContextResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PresentationContextResult_name[_PresentationContextResult_index[i]:_PresentationContextResult_index[i+1]]
}
