// Code generated by "stringer -type RejectResultType -trimprefix ResultRejected"; DO NOT EDIT.

package pdu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResultRejectedPermanent-1]
	_ = x[ResultRejectedTransient-2]
}

const _RejectResultType_name = "PermanentTransient"

var _RejectResultType_index = [...]uint8{0, 9, 18}

func (i RejectResultType) String() string {
	i -= 1
	if i >= RejectResultType(len(_RejectResultType_index)-1) {
		return "RejectResultType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RejectResultType_name[_RejectResultType_index[i]:_RejectResultType_index[i+1]]
}
