// Code generated by "stringer -type RejectReasonType -trimprefix RejectReason"; DO NOT EDIT.

package pdu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RejectReasonNone-1]
	_ = x[RejectReasonApplicationContextNameNotSupported-2]
	_ = x[RejectReasonCallingAETitleNotRecognized-3]
	_ = x[RejectReasonCalledAETitleNotRecognized-7]
}

const (
	_RejectReasonType_name_0 = "NoneApplicationContextNameNotSupportedCallingAETitleNotRecognized"
	_RejectReasonType_name_1 = "CalledAETitleNotRecognized"
)

var (
	_RejectReasonType_index_0 = [...]uint8{0, 4, 38, 65}
)

func (i RejectReasonType) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _RejectReasonType_name_0[_RejectReasonType_index_0[i]:_RejectReasonType_index_0[i+1]]
	case i == 7:
		return _RejectReasonType_name_1
	default:
		return "RejectReasonType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
