// Code generated by "stringer -type SourceType -trimprefix SourceUL"; DO NOT EDIT.

package pdu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SourceULNotSpecified-0]
	_ = x[SourceULServiceUser-1]
	_ = x[SourceULServiceProviderACSE-2]
	_ = x[SourceULServiceProviderPresentation-3]
}

const _SourceType_name = "NotSpecifiedServiceUserServiceProviderACSEServiceProviderPresentation"

var _SourceType_index = [...]uint8{0, 12, 23, 42, 69}

func (i SourceType) String() string {
	if i >= SourceType(len(_SourceType_index)-1) {
		return "SourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SourceType_name[_SourceType_index[i]:_SourceType_index[i+1]]
}
