// Code generated by "stringer -type Type -trimprefix Type"; DO NOT EDIT.

package pdu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeAAssociateRq-1]
	_ = x[TypeAAssociateAc-2]
	_ = x[TypeAAssociateRj-3]
	_ = x[TypePDataTf-4]
	_ = x[TypeAReleaseRq-5]
	_ = x[TypeAReleaseRp-6]
	_ = x[TypeAAbort-7]
}

const _Type_name = "AAssociateRqAAssociateAcAAssociateRjPDataTfAReleaseRqAReleaseRpAAbort"

var _Type_index = [...]uint8{0, 12, 24, 36, 43, 53, 63, 69}

func (i Type) String() string {
	i -= 1
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
